In [1]:
import torch, torchvision
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to C:\Users\Renhao Lu/.cache\torch\hub\checkpoints\resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:13<00:00, 3.58MB/s]


In [2]:
prediction = model(data) # forward pass

In [3]:
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [10]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [15]:
optim.step()

In [16]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [17]:
Q = 3*a**3 - b**2

In [19]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [20]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [18]:
print(Q)

tensor([-12.,  65.], grad_fn=<SubBackward0>)
